### PR TITLE
Handle adding noise like A1111 extension

### PR DESCRIPTION
**Pull request by blepping**
sorry about the deluge of pull requests. 

not sure if you're interested but this is a version that works more like the A1111 extension. it would also be possible to refactor a bit and provide two nodes, one that works like your current one and one that works more like the A1111 version. i think you call their "mix factor" rescale.

(i also relaxed the restrictions on the parameters since stuff like negative values for noise scale or mix factor, etc can be fun to play with.)

### CODE REVIEW

**Comment by asagi4** [comment]
I named things in the function after the original paper.

Is there a reason to use the sqrt function from numpy instead of torch? I also left the rescale parameter out because it's not useful; a mixing factor if zero is equivalent to rescale=False since `y_scaled * psi + (1 - psi) * y` is y if psi is 0.

I don't mind extending the range, but I'd rather not add a parameter that's not needed.

**Comment by asagi4** [comment]
I'll close this.

I relaxed the noise scaling parameter a bit, though not quite up to 100. Allowing the rescale parameter to go past the 0 to 1 range didn't seem very useful.

**Comment by blepping** [comment]
i apologize for leaving this open. it seemed like i got different results with the approach i was using but and i was planning to get back to it and do some double checking and comparing but i got distracted by other stuff.

**Comment by asagi4** [comment]
@blepping no harm done. I like keeping the issues/PRs clean so I tend to close them if they seem stalled, but feel free to send more PRs later if you want.

**Pull request closed without merging**
